model: /models/gpt-oss-20b/
tool-call-parser: openai
reasoning-parser: openai_gptoss 
async-scheduling: True
enable-auto-tool-choice: True 
tensor-parallel-size: 1
gpu-memory-utilization: 0.90 
served-model-name: gpt-oss-20b 
port: 8888 
api-key: my-key
host: 0.0.0.0
